/* MTI_DPI */

/*
 * Copyright 2002-2020 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linuxaloem'
 */
#ifndef INCLUDED_DPIHEADER
#define INCLUDED_DPIHEADER

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
int
c_get_command();

DPI_LINK_DECL DPI_DLLESPEC
int
c_init();

DPI_LINK_DECL DPI_DLLESPEC
int
c_update();

DPI_LINK_DECL DPI_DLLESPEC
char
get_input(
    int id);

DPI_LINK_DECL DPI_DLLESPEC
void
process_output(
    char vga);

#endif 
